export const data = [
  {
    name: "静海区唐官屯镇厂房出租",
    tab: ["价格可面议", "可以分割", "随时可看"],
    position: "静海区-唐官屯镇  | 神州通物流园  |  楼库",
    area: "2550m²",
    areaType: "楼库",
    areaStart: "起租面积",
    areaBuild: "建筑面积",
    priceType: 1, // 1显示新旧价格 2是价格范围
    newPrice: 0.6,
    oldPrice: 0.8,
    unit: "元/m²/天",
    town: "胡家河",
    city: "东丽区新立街",
    location: "静海区唐官屯镇工业园厂房",
    areaDescript: "建筑面积",
    newArea: "1.08",
    oldArea: "1.1",
    areaUnit: "万/月",
    path: "/warehousing/warehousingDetail",
    user: {
      name: "刘朝明",
      company: "天津市瑞和仓储有限公司",
      code: "91120116MAD5ULIK9I",
      tel: "15434564332",
      href: "http://ajgkdjajf9fojda",
    },
  },
  {
    name: "天津国际物流公司睿东物流海运空运-双清包税-国际陆运",
    tab: ["低噪音", "全程跟踪"],
    position: "东莞市莞发物流有限公司   | 全国发货  |  陆运",
    area: "",
    priceType: 2, // 1显示新旧价格 2是价格范围
    newPrice: "68~93",
    oldPrice: "70~100",
    unit: "元",
    town: "胡家河",
    city: "江苏市姑苏区",
    location: "江苏省苏州市姑苏区苏州传化公路港",
    path: "/warehousing/logisticDetail",
    user: {
      name: "刘朝明",
      company: "天津市瑞和仓储有限公司",
      code: "91120116MAD5ULIK9I",
      tel: "13678623333",
      href: "http://ajgkdjajf9fojda",
    },
  },
];
